SELECT *
FROM customer

--1.What is the total revenue generated by male vs female customer?
SELECT gender,SUM(purchase_Amount) AS total_revenue
FROM customer
GROUP BY gender;

--2.Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

--3.Which are the top 5 products with the highest average review rating?
SELECT item_purchased,AVG(review_ratiNg) AS average_rating
FROM customer
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

--4.Compare the average purchase amount between Standard and Express Shipping.
SELECT shipping_type,AVG(purchase_amount) AS average_amount
FROM customer
WHERE shipping_type IN('Standard','Express')
GROUP BY 1;

--5.Do subscriped customer spend more? Compare average spend and total revenue betwwen subscriber and non-subscriber.
SELECT subscription_status,
COUNT(customer_id) AS total_cutomer,
AVG(purchase_amount) AS average_amount,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY 1
ORDER BY 3,2 DESC;

--6.Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
round(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) / count(*),2) AS purchase_rate
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;

--7.Segment customer into New, Returning, Loyal based on their total number of previous purchases, show the count of each segment.
WITH c1 AS (
SELECT customer_id,previous_purchases,
     CASE WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
     END AS customer_type
FROM customer
)

SELECT customer_type,COUNT(customer_id) AS total_customer
FROM c1 
GROUP BY 1
ORDER BY 2;

--8.What are the top 3 most purchased products within each category.
WITH c1 AS(
SELECT category,item_purchased,COUNT(customer_id) AS total_purchase,
RANK()OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rnk
FROM customer
GROUP BY category,item_purchased
)

SELECT category,item_purchased,total_purchase
FROM c1
WHERE rnk IN(1,2,3);


--9.Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscriber?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY 1;


--10.What is the revenue contribution of each group?
SELECT "Age_Group",
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY "Age_Group"
ORDER BY 2 DESC;